#!/usr/bin/ruby
require 'rubygems'
require 'redis'
r = Redis.new

datapoints = r.smembers "datapoints"; nil
datapoint_keys = r.keys("timers:*") + r.keys("counters:*"); nil
stale_keys = datapoint_keys - datapoints; nil

stale_keys.each{|k| r.del k}; nil
